2025-08-19 10:44:17,504 INFO: Test task [in B:\IT\Web\copy\backend\app\__init__.py:33]
2025-08-19 10:59:55,755 INFO: Test task [in B:\IT\Web\copy\backend\app\__init__.py:33]
2025-08-19 11:07:49,487 INFO: Test task [in B:\IT\Web\copy\backend\app\__init__.py:33]
2025-08-19 11:23:07,899 INFO: Test task [in B:\IT\Web\copy\backend\app\__init__.py:33]
2025-08-19 11:41:08,642 INFO: Test task [in B:\IT\Web\copy\backend\app\__init__.py:33]
2025-08-19 19:15:13,621 INFO: Test task [in B:\IT\Web\copy3\backend\app\__init__.py:33]
2025-08-19 19:49:19,241 ERROR: Exception on /api/work_types [POST] [in B:\IT\Web\test_task2\backend\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\engine\default.py", line 945, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: work_types.name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "B:\IT\Web\copy3\backend\app\api\handlers.py", line 314, in create_work_type
    db.session.commit()
    ~~~~~~~~~~~~~~~~~^^
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\orm\scoping.py", line 599, in commit
    return self._proxied.commit()
           ~~~~~~~~~~~~~~~~~~~~^^
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\orm\session.py", line 2032, in commit
    trans.commit(_to_root=True)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<string>", line 2, in commit
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\orm\session.py", line 1313, in commit
    self._prepare_impl()
    ~~~~~~~~~~~~~~~~~~^^
  File "<string>", line 2, in _prepare_impl
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\orm\session.py", line 1288, in _prepare_impl
    self.session.flush()
    ~~~~~~~~~~~~~~~~~~^^
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\orm\session.py", line 4353, in flush
    self._flush(objects)
    ~~~~~~~~~~~^^^^^^^^^
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\orm\session.py", line 4488, in _flush
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\orm\session.py", line 4449, in _flush
    flush_context.execute()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
    ~~~~~~~~~~~^^^^^^
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.mapper,
        ^^^^^^^^^^^^
        uow.states_for_mapper_hierarchy(self.mapper, False, False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        uow,
        ^^^^
    )
    ^
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        base_mapper,
        ^^^^^^^^^^^^
    ...<3 lines>...
        insert,
        ^^^^^^^
    )
    ^
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
        statement,
        params,
        execution_options=execution_options,
    )
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
        self,
        distilled_parameters,
        execution_options or NO_OPTIONS,
    )
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\sql\elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, distilled_params, execution_options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
        dialect,
    ...<8 lines>...
        cache_hit=cache_hit,
    )
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\engine\base.py", line 1843, in _execute_context
    return self._exec_single_context(
           ~~~~~~~~~~~~~~~~~~~~~~~~~^
        dialect, context, statement, parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\engine\base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e, str_statement, effective_parameters, cursor, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\engine\base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "B:\IT\Web\test_task2\backend\Lib\site-packages\sqlalchemy\engine\default.py", line 945, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: work_types.name
[SQL: INSERT INTO work_types (name, "order", color, category) VALUES (?, ?, ?, ?)]
[parameters: ('Штукатурка', 1, '#e53e3e', 'Черновые')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-08-19 19:51:03,693 INFO: Test task [in B:\IT\Web\copy3\backend\app\__init__.py:33]
2025-08-19 19:55:45,758 INFO: Test task [in B:\IT\Web\copy3\backend\app\__init__.py:33]
2025-08-19 21:19:59,485 INFO: Test task [in B:\IT\Web\copy3\backend\app\__init__.py:33]
2025-08-19 22:20:46,994 INFO: Test task [in B:\IT\Web\copy3\backend\app\__init__.py:33]
2025-08-19 22:33:02,231 INFO: Test task [in B:\IT\Web\copy3\backend\app\__init__.py:33]
2025-08-20 10:03:26,746 INFO: Test task [in B:\IT\Web\test_task2\backend\app\__init__.py:33]
2025-08-20 10:20:15,265 INFO: Test task [in B:\IT\Web\test_task2\backend\app\__init__.py:33]
2025-08-20 10:32:00,610 INFO: Test task [in B:\IT\Web\test_task2\backend\app\__init__.py:33]
2025-08-20 10:32:56,420 INFO: Test task [in B:\IT\Web\test_task2\backend\app\__init__.py:33]
2025-08-20 10:42:51,239 INFO: Test task [in B:\IT\Web\test_task2\backend\app\__init__.py:33]
2025-08-20 10:45:45,775 INFO: Test task [in B:\IT\Web\test_task2\backend\app\__init__.py:33]
